MySQL:
  host: localhost
  db: divecrafts
  user: root
  pass: patata123
disguises:
  - 'Steve'
  - 'Alex'
Permissions:
  0:
    perms:
      - ''
    noheredar:
      - ''
  1:
    perms:
      - ''
    noheredar:
      - ''
  2:
    perms:
      - ''
    noheredar:
      - ''
  3:
    perms:
      - ''
    noheredar:
      - ''
  4:
    perms:
      - ''
    noheredar:
      - ''
  5:
    perms:
      - ''
    noheredar:
      - ''
  6:
    perms:
      - ''
    noheredar:
      - ''
  7:
    perms:
      - ''
    noheredar:
      - ''
  8:
    perms:
      - ''
    noheredar:
      - ''
  9:
    perms:
      - ''
    noheredar:
      - ''
  10:
    perms:
      - ''
    noheredar:
      - ''
  11:
    perms:
      - ''
    noheredar:
      - ''
  12:
    perms:
      - ''
    noheredar:
      - ''
  13:
    perms:
      - ''
    noheredar:
      - ''
Holograms:
  - ''