name: Essentials
version: 1.0
author: clonalejandro
description: §fdescripción§f:§a Plugin essentials para survival
main: io.clonalejandro.Essentials.Main
commands:
  exp:
    usage: /<command>
  heal:
    usage: /<command>
  feed:
    usage: /<command>
  fly:
    usage: /<command>
  clear:
    usage: /<command>
    aliases:
      - clearinventory
      - ci
  gamemode:
    aliases:
      - gm
    usage: /<command>
  hat:
    usage: /<command>
  god:
    usage: /<command>
  speed:
    usage: /<command>
  time:
    usage: /<command>
  vanish:
    usage: /<command>
    aliases:
      - v
  tpa:
    usage: /<command>
  tpaall:
    usage: /<command>
  tpahere:
    usage: /<command>
  tpaccept:
    usage: /<command>
  tpdeny:
    usage: /<command>
  tp:
    usage: /<command>
  tphere:
    usage: /<command>
  tpall:
    usage: /<command>
  invsee:
    usage: /<command>
  spawn:
    usage: /<command>
  setspawn:
    usage: /<command>
  sethome:
    usage: /<command>
  home:
    usage: /<command>
    aliases:
      - homes
  delhome:
    usage: /<command>
  warp:
    usage: /<command>
  setwarp:
    usage: /<command>
  delwarp:
    usage: /<command>
  warps:
    usage: /<command>
  back:
    usage: /<command>
  broadcast:
    usage: /<command>
  iteminfo:
    usage: /<command>
  balance:
    usage: /<command>
    aliases:
      - bal
  balanceTop:
    usage: /<command>
    aliases:
      - baltop
  deposit:
    usage: /<command>
  withdraw:
    usage: /<command>