MySQL:
  host: localhost
  db: divecrafts
  user: root
  pass: patata123
Permissions:
  0:
    perms:
      - ''
    noheredar:
      - ''
  1:
    perms:
      - ''
    noheredar:
      - ''
  2:
    perms:
      - ''
    noheredar:
      - ''
  3:
    perms:
      - ''
    noheredar:
      - ''
  4:
    perms:
      - ''
    noheredar:
      - ''
  5:
    perms:
      - ''
    noheredar:
      - ''
  6:
    perms:
      - ''
    noheredar:
      - ''
  7:
    perms:
      - ''
    noheredar:
      - ''
  8:
    perms:
      - ''
    noheredar:
      - ''