###########################################################
#  _    _ _    _  _____    _____          __  __ ______   #
# | |  | | |  | |/ ____|  / ____|   /\   |  \/  |  ____|  #
# | |  | | |__| | |      | |  __   /  \  | \  / | |__     #
# | |  | |  __  | |      | | |_ | / /\ \ | |\/| |  __|    #
# | |__| | |  | | |____  | |__| |/ ____ \| |  | | |____   #
#  \____/|_|  |_|\_____|  \_____/_/    \_\_|  |_|______|  #
#                                                         #
###########################################################


#############################################################################################
# Developed by clonalejandro                                                                #
#                                                                                           #
# -= SOCIAL NETWORKS =-                                                                     #
#                                                                                           #
# Website: https://clonalejandro.me                                                         #
# GitHub: https://github.com/clonalejandro                                                  #
# GitLab: https://gitlab.com/clonalejandro                                                  #
# YouTube: https://youtube.com/c/clonalejandromcbGameplays                                  #
# Twitter: https://twitter.com/clonalejandro11                                              #
# Google+: https://plus.google.com/u/0/+clonalejandromcbGameplays                           #
# Spigot: https://www.spigotmc.org/members/clonalejandro.28979/                             #
# Bukkit: https://bukkit.org/members/clonalejandro.91257534/                                #
# GoogleScholar: https://scholar.google.es/citations?user=DiDtLgoAAAAJ&hl=es                #
# McMarket: http://www.mc-market.org/members/34499/                                         #
# Enjin: https://www.enjin.com/profile/13291450                                             #
# KeyBase: https://keybase.io/clonalejandro                                                 #
# XenForo: https://xenfacil.com/miembros/clonalejandro.1764/                                #
# SpainPvP: https://spainpvp.com/members/clonalejandro.956/                                 #
# DevBukkit: https://dev.bukkit.org/members/clonalejandro                                   #
# SoundCloud: https://soundcloud.com/clonalejandro-mcb                                      #
# Steam: https://steamcommunity.com/id/clonalejandro                                        #
# StackOverFlow: https://stackoverflow.com/users/8099410/clonalejandro-mcb                  #
# StackExChange: https://stackexchange.com/users/11026741/clonalejandro-mcb                 #
# SocialBlade: https://socialblade.com/youtube/channel/UCGjUzh0rhZQeK_bdz4QcDIg             #
# Sellfy: https://sellfy.com/clonalejandro                                                  #
# Ask: https://ask.fm/alejandro_prc                                                         #
#############################################################################################

Debug: false

host: "clonalejandro"

Game:
  Mode: "FFA" # This variable set the mode of this game
  CountDown: 45 # This is de countdown in seconds per start the game
  MinPlayers: 2 # This is the min of the players for the game start the CountDown
  UhcWorldMobLimit: 400 # This is the limit of mobs in the normal world of this game
  UhcNetherMobLimit: 150 # This is the limit of mobs in the nether world of this game
  AirDropTime: 300 # Time in seconds for throw new AirDrop to the game

Map:
  CenterX: 00.00 # This represent a X Coord center of the UHC map
  CenterZ: 00.00 # This represent a Z Coord center of the UHC map
  Width: 750 # This represent a Radius of UHC map